//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASOC_PLANRECURSOS
    {
        public int Id { get; set; }
        public int ID_RECURSO { get; set; }
        public int ID_TAREA { get; set; }
    }
}
